spring:
  application:
    name: demo
  cloud:
    vault:
      uri: http://192.168.0.193:8200
      token: hvs.8BV9BpKW2rsmLy3eXqD6Uu92
      kv:
        enabled: true
        backend: services
        application-name: demo
  config:
    import: vault://
  profiles:
    active: dev
server:
  port: 8080
