
DB_HOST: jdbc:postgresql://192.168.0.193:5432
DB_PASS: postgres
DB_USER: postgres
DB_NAME: postgres
DB_DRIVER: org.postgresql.Driver

NAME: ${prueba}:texto name si no encuentra vault

test: ${kv-test}:texto test si encuetra vault
